### ISSUE TITLE
Using AndroidWorld with physical Android devices

### ISSUE THREAD

**Issue by derekywk** [google-research/android_world#121]
Hello there, thank you for your impressive work on the AndroidWorld.
I've been running AndroidWorld and its agents on emulators successfully. But I wonder if there'd be any ways to make it work on physical devices as well?
The problem here should be the setup of a grpc bridge between the device and host machine, which is impossible to bypass if we wanna to access to the a11y tree I guess.
Do you have any experiences doing this? Any guidance would be appreciated. Thank you!

**Comment by kenjitoyama** [comment]
Hello @derekywk, I tested [AndroidEnv](https://github.com/google-deepmind/android_env) (the underlying infra in AndroidWorld) on physical devices and it did work. As you said, you will need gRPC open (it's an egress connection from the point of view of the device), but once that's done, it should be able to connect.
We did have a few issues with the internal firewall in Android blocking connections in some devices, but after you disable that it should work.

Cheers,

Daniel

**Comment by derekywk** [comment]
Hi Daniel, thank you for your prompt reply. Glad to hear that it worked. For the gRPC connection, since I don't have much experiment on such setup, may I ask if there is any opensource codebase that you used for the test? Thanks in advance!

Cheers,
Derek

**Comment by kenjitoyama** [comment]
Hi again, @derekywk. There was nothing special to handle gRPC. [`A11yGrpcWrapper`](https://github.com/google-deepmind/android_env/blob/main/android_env/wrappers/a11y_grpc_wrapper.py) already handles connecting to the device via gRPC and fetching A11y trees. It's mostly a configuration of the device itself to ensure that the connection can be established.

**Comment by derekywk** [comment]
Hi Daniel, thank you for your previous response. I have installed the AccessibilityForwarder on my physical device, and, by default, the device doesn't have gRPC open. I wonder if the [_configure_grpc](https://github.com/google-deepmind/android_env/blob/main/android_env/wrappers/a11y_grpc_wrapper.py#L269) function (specifically the following command) in A11yGrpcWrapper is sufficient to set up the gRPC server on the device from scratch?
`adb shell am broadcast -a accessibility_forwarder.intent.action.SET_GRPC --ei port <port_number> -n com.google.androidenv.accessibilityforwarder/com.google.androidenv.accessibilityforwarder.FlagsBroadcastReceiver`
My device still fails to connect via grpc.secure_channel() in [_connect_to_emulator](https://github.com/google-deepmind/android_env/blob/main/android_env/components/simulators/emulator/emulator_simulator.py#L330) within emulator_simulator.py. I would greatly appreciate any guidance you could provide on resolving this issue.

**Comment by kenjitoyama** [comment]
Hi @derekywk, that function should set up gRPC, yes.

The reason it is this way is because, as of now, running [gRPC servers on Android is not supported](https://grpc.io/docs/platforms/android/java/quickstart/), so we run the gRPC server in Python (spawned by `A11yGrpcWrapper`) and the client in Android (`AccessibilityForwarder` app). There is no "discovery" mechanism, so this broadcast message tells the app which host and port number to connect to.

@crawles , we should increase the priority of releasing the source code of `AccessibilityForwarder` so that other people can see what goes on in there, and also to modify it (e.g. adding log lines etc).

**Comment by derekywk** [comment]
Hi @kenjitoyama, thank you for your clarification. I now have the gRPC server and client set up, but the client on the physical device is still unable to send messages, whereas the same setup works on an emulator.. Below is the log from device. I suspect this might be related to proxy or internal firewall in Android you mentioned earlier. Since 10.0.2.2 only works for emulator, should we simply replace it with the local IPv4 address along with port forwarding? Also, to disable internal firewall, would rooting be absolutely necessary? Thanks in advance!

> gRPC StatusException; are you sure networking is turned on?
> extra: exception ['io.grpc.StatusException: UNAVAILABLE: End of stream or IOException']
> tagSocket(101) with statsTag=0xffffffff, statsUid=-1
> tagSocket(99) with statsTag=0xffffffff, statsUid=-1
> tagSocket(100) with statsTag=0xffffffff, statsUid=-1

**Comment by derekywk** [comment]
Hi there. I have successfully resolved the issue by adding an extra host 127.0.0.1 and using `adb reverse`. Thank you for your assistance and for releasing the source code of AccessibilityForwarder. Cheers! :)

**Comment by kenjitoyama** [comment]
Hi @derekywk , thanks for reporting it back to let us know that it worked. Good luck with your research!

**Comment by MaginaDai** [comment]
Hi Dear @derekywk, I am currently exploring the use of physical devices. Would it be possible for you to share your code related to this aspect? Thanks a lot!!!

**Comment by kenjitoyama** [comment]
Hi @MaginaDai, you can change the server address with `-es host <host>`.

We really need to open source the code for the app, then it'll be clear how to do these things. For now please try with that flag.

Thanks

**Comment by MaginaDai** [comment]
> Hi @MaginaDai, you can change the server address with `-es host <host>`.
> 
> We really need to open source the code for the app, then it'll be clear how to do these things. For now please try with that flag.
> 
> Thanks


Hi,
  Thanks for your reply.  I have set with --es host <host_ip>. I have also used adb reverse tcp:8554 tcp:8554 to set up the forward path from the device to the server.  Notice that in a11y_grpc_wrapper.py, the port is set as an arbitrary unused port (not 8554). I manually set it to 8554. But found there is still some error: 
  
  0-16 13:52:44.448 16370 16397 I AndroidRLTask: sending (blocking) gRPC request for tree.
10-16 13:52:45.455 16370 16397 W AndroidRLTask: gRPC TimeoutCancellationException; are you sure networking is turned on?
 
 Could you please share some insights on this?

**Comment by crawles** [comment]
As a temporary workaround, until the forwarder is resolved, you can set the A11yMethod to use `UIAUTOMATOR` [here](https://github.com/google-research/android_world/blob/main/android_world/env/android_world_controller.py#L148). This bypasses the `a11y_grpc_wrapper.py` logic. However it is a bit slower, but should get you going

**Comment by kenjitoyama** [comment]
Hi, sorry this will be hard to debug from our end. In a nutshell, the accessibility forwarder app must be able to reach the grpc server running within the a11ygrpcwrapper. From our experience, most of the problems were related to the device's firewall blocking egress requests.

I am open sourcing the app in this pull request: https://github.com/google-deepmind/android_env/pull/232

You are welcome to compile it yourself and try it with more logging and different settings.

**Comment by MaginaDai** [comment]
> Hi, sorry this will be hard to debug from our end. In a nutshell, the accessibility forwarder app must be able to reach the grpc server running within the a11ygrpcwrapper. From our experience, most of the problems were related to the device's firewall blocking egress requests.
> 
> I am open sourcing the app in this pull request: [google-deepmind/android_env#232](https://github.com/google-deepmind/android_env/pull/232)
> 
> You are welcome to compile it yourself and try it with more logging and different settings.

Hi thanks for your quick reply.
During the debugging, another problem is we meet is that our PC sometimes fail to build the gRPC connection to the phone in the _connect_to_emulator function in emulator_simulator.py. I notice that the grpc server is initialized at a11y_grpc_wrapper.py, which is executed later than the _connect_to_emulator function. May I confirm whether the logic is correct? 

However, this problem sometimes disappears by itself. I have no idea of what is happening

**Comment by kenjitoyama** [comment]
Hi again, I think there's a misunderstanding here. If you're using a physical device, you shouldn't be using `EmulatorSimulator` since that's for talking to an Android Emulator binary. In the specific case of AndroidWorld and a physical device, the agent can basically run blind wrt pixels and rely solely on a11y trees and events.

If you also need pixels from a physical device, then it would be necessary to grab them via the screen recording functionality (https://developer.android.com/media/grow/media-projection) in an app. But we haven't packaged that in an easy-to-use `BaseSimulator` implementation. Perhaps that would be a feature request for the `AccessibilityForwarder` app (but at that point it should probably be called something else), or it could be a separate app that could also connect to Python via gRPC.

Cheers

**Comment by kenjitoyama** [comment]
Hi @Jeffjeno,

Android provides a lot of accessibility information, too much even, and we don't forward all of that to AndroidEnv. Please take a look at https://github.com/google-deepmind/android_env/blob/main/android_env/apps/java/com/google/androidenv/accessibilityforwarder/AccessibilityTreeCreator.kt for details of the data that's extracted. Let us know if there's crucial data that we're ignoring.

Cheers,

Daniel

**Comment by Jeffjeno** [comment]
> Hi [@Jeffjeno](https://github.com/Jeffjeno),
> 
> Android provides a lot of accessibility information, too much even, and we don't forward all of that to AndroidEnv. Please take a look at https://github.com/google-deepmind/android_env/blob/main/android_env/apps/java/com/google/androidenv/accessibilityforwarder/AccessibilityTreeCreator.kt for details of the data that's extracted. Let us know if there's crucial data that we're ignoring.
> 
> Cheers,
> 
> Daniel

Hi @kenjitoyama,
Thanks for your reply!
My main question is: for Android World evaluations, can UIAutomator be used as a drop-in replacement for A11y_Forwarder as the UI-tree source?
I’m not sure whether switching from A11y_Forwarder to UIAutomator would affect the evaluation results.

Best, jeff
