### ISSUE TITLE
[Errno 2] No such file or directory: '/tmp/default.textproto'

### ISSUE THREAD

**Issue by lsy641** [google-research/android_world#145]
Hi, thanks for reading my question. I am a beginner at using your benchmark. When I tried to run the minimal task by following your instruction, "python minimal_task_runner.py --task=ContactsAddContact", it returns me with [Errno 2] No such file or directory: '/tmp/default.textproto'. 
Can I have a quick answer for that?

**Comment by crawles** [comment]
Can you please share the full stacktrace?

**Comment by petrichor20211** [comment]
> Hi, thanks for reading my question. I am a beginner at using your benchmark. When I tried to run the minimal task by following your instruction, "python minimal_task_runner.py --task=ContactsAddContact", it returns me with [Errno 2] No such file or directory: '/tmp/default.textproto'.您好，感谢阅读我的问题。我是使用您基准测试的新手。当我按照您的指示尝试运行最小任务时，“python minimal_task_runner.py --task=ContactsAddContact”，它返回给我[Errno 2]没有找到文件或目录：'/tmp/default.textproto'。 Can I have a quick answer for that?我能快速得到那个答案吗？

Have you solved it yet? I also encountered the same problem

**Comment by petrichor20211** [comment]
![image](https://github.com/user-attachments/assets/7a03a401-d0dc-450e-89e0-f58d8745e7bc)

**Comment by crawles** [comment]
Ah, this is probably because it's for windows and `/tmp` doesn't exist. You can TAL at https://github.com/google-research/android_world/issues/117 for some tips for windows
