### ISSUE TITLE
Guidance Needed for Installing New App

### ISSUE THREAD

**Issue by njucckevin** [google-research/android_world#157]
Thank you for providing such a great project. I am trying to install a new app in the androidworld and build a script similar to `minimal_task_runner.py` to test its task completion. Could you provide some guidance on how to install a new app, like the Wikipedia app (https://f-droid.org/en/packages/org.wikipedia/) I found on froid.org?
I think I need to add a new task in `task_metadata.json`, but I'm unsure how to modify the other parts. I would appreciate your help.
P.S. I followed this issue (https://github.com/google-research/android_world/issues/118) to install the app, but I encountered the same permission issue on a Pixel 6a device. Is it possible to drag the APK directly into the Pixel 6 adv for new app installation?
Thank you very much!

**Comment by crawles** [comment]
Hi, in order to install a new app, the easiest way is to simply do `adb_utils.install_apk(path, env.controller)`, where in your case `path` would be the `~/Downloads/wikipeida_app.apk`. If you need to perform some setup logic, you may want to create a setup class for it. E.g.,

```
from android_world.env.setup_device.setup import setup, apps
setup.setup_app(apps.SimpleSMSMessengerApp, env) # TODO: Create one for Wikipedia.
```

In order to create a new task for the app, we wrote [this guide](https://github.com/google-research/android_world/blob/main/docs/tasks_guide.md) which may be of use. `task_metadata.json` is just for informational purposes and not referenced in the code.

**Comment by crawles** [comment]
Also for testing purposes, you can also just install Wikipedia app from the playstore. I will take a close look at https://github.com/google-research/android_world/issues/118

**Comment by njucckevin** [comment]
Hi, I have another question about the AndroidWorld environment and evaluation. I followed the setup at https://github.com/google-research/android_world#installation, and everything seems ok. 
Then, I tried to install the necessary apps for evaluation by running the following code:
```
python run.py \
  --suite_family=android_world \
  --agent_name=t3a_gpt4 \
  --perform_emulator_setup \
  --tasks=ContactsAddContact,ClockStopWatchRunning \ 
```
During the script running I encountered：
```
E1106 20:17:15.426124 8646469120 adb_controller.py:131] Failed to execute ADB command (try 2 of 3): [adb -P 5037 -s emulator-5554 install /tmp/android_world/app_data/org.videolan.vlc_13050408.apk]
Traceback (most recent call last):
  File "/Users/cckevin/opt/anaconda3/envs/android_world/lib/python3.11/site-packages/android_env-1.2.2-py3.11.egg/android_env/components/adb_controller.py", line 122, in execute_command
    cmd_output = subprocess.check_output(
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cckevin/opt/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cckevin/opt/anaconda3/envs/android_world/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/cckevin/Library/Android/sdk/platform-tools/adb', '-P', '5037', '-s', 'emulator-5554', 'install', '/tmp/android_world/app_data/org.videolan.vlc_13050408.apk']' returned non-zero exit status 1.
```
The program then continues to run, and appears to be installing the various apps. But there are some warnings in the process, e.g.,
```
W1106 20:19:02.495772 8646469120 setup.py:116] Failed to automatically setup app markor: Target text "Allow access to manage all files" not found..

You will need to manually setup the app.
```
Finally, the evaluation of the agent seems correct:
```
                             task_num  num_complete_trials  mean_success_rate  mean_episode_length  total_runtime_s  num_fail_trials
task                                                                                                                                
ClockStopWatchRunning               0                  1.0                1.0                  4.0             44.3              0.0
========= Average =========         0                  1.0                1.0                  4.0             44.3              0.0
```
I want to make sure, that my AndroidWorld is configured correctly? Are these warnings and errors not affecting the way I use it?
Thanks a lot!

**Comment by crawles** [comment]
Hmm. Yeah, so we setup each app individually. In your particular case you ran the agent on a stopwatch task, which uses the built-in clock app, which require no additional setup.

In the error you provided, VLC player seems to not correctly have been installed. Can you check if it's installed? Can you please show the output of `ls /tmp/android_world/app_data`? Maybe somehow it didn't get downloaded?

As for the Markor issue, `Allow access to manage all files` that is likely due to the setup on Pixel 6a is a little different vs. Pixel 6.

What I'd recommend is if you want to run the benchmark (i.e the 116 tasks) and report numbers that other people can compare with, use Pixel 6. If you want to experiment and try new apps etc use Pixel 6a. Even with 6a, Markor and other apps should be fine since we are just installing them and doing some basic setup stuff. There just may be slight differences that make it a little hard to directly compare agent results to Pixel 6.

**Comment by njucckevin** [comment]
Thanks for the quick reply. In fact, all of my configurations above were done on Pixel 6, following the standard tutorial you provided in order to evaluate on the benchmark.
The VLC seems be installed successfully (and I can find the four videos). The `ls /tmp/android_world/app_data` output: 
```
(android_world) chengkanzhideMacBook-Pro:android_world cckevin$ ls /tmp/android_world/app_data
Liechtenstein_europe.obf                        com.simplemobiletools.calendar.pro_238.apk      net.gsantner.markor_146.apk
androidworld.apk                                com.simplemobiletools.draw.pro_79.apk           net.osmand-4.6.13.apk
clipper.apk                                     com.simplemobiletools.gallery.pro_396.apk       org.tasks_130605.apk
code.name.monkey.retromusic_10603.apk           com.simplemobiletools.smsmessenger_85.apk       org.videolan.vlc_13050407.apk
com.arduia.expense_11.apk                       de.dennisguse.opentracks_5705.apk               org.videolan.vlc_13050408.apk
com.dimowner.audiorecorder_926.apk              miniwobapp.apk
com.flauschcode.broccoli_1020600.apk            net.cozic.joplin_2097740.apk
```
<img width="420" alt="截屏2024-11-07 10 24 24" src="https://github.com/user-attachments/assets/757eb6e6-cd89-4e9d-954a-bcd6a97fed9c">

There are some warnings about manually setup the apps:
```
Setting up applications on Android device. Please do not interact with device while installation is running.
W1107 10:18:47.422768 8639198720 setup.py:116] Failed to automatically setup app contacts: Target text "Don't allow" not found..

You will need to manually setup the app.
W1107 10:19:50.701442 8639198720 setup.py:116] Failed to automatically setup app activity tracker: Target text "Allow" not found..

You will need to manually setup the app.
W1107 10:20:24.807858 8639198720 setup.py:116] Failed to automatically setup app simple sms messenger: Target text "SMS Messenger" not found..

You will need to manually setup the app.
Initializing agent...
```
I tried opening the apps and didn't find any obvious problems. For example, the demo t3a_gpt4 agent can don the task on Contacts:
```
                             task_num  num_complete_trials  mean_success_rate  mean_episode_length  total_runtime_s  num_fail_trials
task                                                                                                                                
ClockStopWatchRunning               0                  1.0                1.0                  4.0             45.5              0.0
ContactsAddContact                  1                  1.0                1.0                  8.0            110.1              0.0
========= Average =========         0                  1.0                1.0                  6.0             77.8              0.0
```
Do I need to do anything to make sure the config is done correctly?

**Comment by njucckevin** [comment]
btw, my computer is macos with apple silicon, so I choose the Tiramisu with arm64 version.

**Comment by crawles** [comment]
Okay got it. I suspect everything is already setup. To be safe, I would
recommend re-creating a Pixel 6 emulator in Android Studio, and then
running the setup script.

Note: once you run it once you will encounter these type of errors the
second time and after. In other words, it’s a one-time setup script. And
running it again will not really have any effect.

**Comment by njucckevin** [comment]
Yes I got it. The first time I encounter three of these 'You will need to manually setup the app.' warnings. And the second time I encounter more these warnings, since some apps has been setup before, I understand.
I'm just about ready to ignore these warnings and start evaluation. Thanks for your help.

**Comment by crawles** [comment]
Okay. I think you are ready to get started with the evaluation.
In the meantime, I will see if I can reproduce the issue. Another option is
I can provide a snapshot of a fully set up emulator.

Chris

**Comment by crawles** [comment]
The issues from the above with setup script should be fixed with: https://github.com/google-research/android_world/pull/168. Specifically the issues like `Target text "SMS Messenger" not found..`
If you'd like you can re-run the setup script on a fresh emulator. As I said, it shouldn't make a huge difference, but should make your app setup standardized for running eval.

**Comment by njucckevin** [comment]
Nice, thank you
