### ISSUE TITLE
How to evaluate information retrieval task?

### ISSUE THREAD

**Issue by cjfcsjt** [google-research/android_world#172]
I do not find any evaluation function for information retrieval tasks, such as SimpleCalendarFirstEventAfterStartTime. Do I miss something?

**Comment by crawles** [comment]
Are you talking about how to run information retrieval tasks? Or are you wondering how the code works? For the first part, you can do: 

```
python run.py \
  --suite_family=android_world \
  --agent_name=t3a_gpt4 \
  --perform_emulator_setup \
  --tasks= SimpleCalendarFirstEventAfterStartTime \  # Optional: Just run on a subset.
```

In terms of how the code works the task is defined [in a proto](https://github.com/google-research/android_world/blob/main/android_world/task_evals/information_retrieval/proto/tasks.textproto#L858-L964). The information retrieval tasks use a different structure in the code, using a proto. Then all information_retrieval tasks share a common `is_successful` ([link](https://github.com/google-research/android_world/blob/main/android_world/task_evals/information_retrieval/information_retrieval.py#L117)) which uses the proto to check for success.
