### ISSUE TITLE
[QUESTION] Can Android World  swipe?

### ISSUE THREAD

**Issue by LYXFOREVER** [google-research/android_world#186]
In t3a.py , function step(self, goal: str), I found this code:

if converted_action.action_type in ['click', 'long-press', 'input-text']:

It seems that android world can only click, long-press or input-text. It seems not to be able to swipe? What should it do if it meets some tasks that need swiping?

**Comment by crawles** [comment]
Hi, yes, swipe is supported. The T3A agent can issue a [`scroll` action](https://github.com/google-research/android_world/blob/main/android_world/agents/t3a.py#L66). A scroll action is simply the inverse of a swipe.  E.g., tin order to scroll down, the agent "swipes" up. Here is the code: https://github.com/google-research/android_world/blob/main/android_world/env/actuation.py#L101

**Comment by LYXFOREVER** [comment]
> Hi, yes, swipe is supported. The T3A agent can issue a [`scroll` action](https://github.com/google-research/android_world/blob/main/android_world/agents/t3a.py#L66). A scroll action is simply the inverse of a swipe. E.g., tin order to scroll down, the agent "swipes" up. Here is the code: https://github.com/google-research/android_world/blob/main/android_world/env/actuation.py#L101

Thank you! I will read the code more carefully.
