### ISSUE TITLE
[Question] Can it be used with automotive emulator?

### ISSUE THREAD

**Issue by ThakurAnunaya** [google-research/android_world#188]
Hi 

I mostly work with automotive emulators? Can this tool be used with automotive emulators?

**Comment by crawles** [comment]
Yes, it should be able to work with automotive emulators, although we have not tried it. The benchmark standarizes on Pixel 6/API 33, however we have succesfully tested it on other Android versions

**Comment by crawles** [comment]
I have successfully tested it with an automotive emulator and it works. Please reopen if you have questions or issues.
