### ISSUE TITLE
[QUESTION] Some problem with the bbox_pixels

### ISSUE THREAD

**Issue by LYXFOREVER** [google-research/android_world#189]
![4](https://github.com/user-attachments/assets/1fbc6092-9ffe-4957-860e-4a935142aef9)

I try to store the history list to make a dataset, but I met a problem

I drew the UI boundaries corresponding to the screenshot onto the image and also plotted the actions. The coordinates of the actions represent the centers of the UI elements. I found that the action coordinates are accurate, but the UI boundaries look a bit off. Even though the coordinates are obtained through the bbox_pixels of the UIElement, why is there such a discrepancy?

**Comment by crawles** [comment]
Is it possible it is a plotting error? Can you share your code you used to plot this?

**Comment by LYXFOREVER** [comment]
> Is it possible it is a plotting error? Can you share your code you used to plot this?

I store the history as .pkl file in minimal_task_runner.py:

with open(path, 'wb') as file:
    pickle.dump(agent.history, file)

Then in another read_history.py file I read the .pkl file:


import pickle
from pathlib import Path
from datetime import datetime
from PIL import Image
import numpy as np
import json

from PIL import Image
import json

import matplotlib.pyplot as plt
from matplotlib import patches
import matplotlib
matplotlib.use('TkAgg')  # 或者 'Agg'

from android_world.agents import agent_utils
from android_world.agents import base_agent
from android_world.agents import infer
from android_world.agents import m3a_utils
from android_world.env import adb_utils
from android_world.env import interface
from android_world.env import json_action
from android_world.env import representation_utils

#默认读取的是bilibili文件夹中的图像
_ACTION_COLOR = 'blue'

def check_pkl():
    pkl_name = 'raw_history_pkl/2024_11_21_16_10_30_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    par_doc_name = 'processed_history/'
    current_time = datetime.now()# 获取当前时间
    formatted_time = current_time.strftime("%Y_%m_%d_%H_%M_%S")# 格式化时间为 年_月_日_时_分_秒
    doc_name = par_doc_name + formatted_time

    # 创建本个pkl文件的文件夹
    folder_path = Path(doc_name)
    if not folder_path.exists():
        folder_path.mkdir(parents=True)  # parents=True 允许创建多级目录
        print(f"文件夹 '{folder_path}' 已创建")
    else:
        print(f"文件夹 '{folder_path}' 已存在")

    for i, step in enumerate(history):
        # 创建本step的文件夹
        step_doc = doc_name + '/' + str(i) + '/'
        folder_path = Path(step_doc)
        if not folder_path.exists():
            folder_path.mkdir(parents=True)  # parents=True 允许创建多级目录
            print(f"文件夹 '{folder_path}' 已创建")
        else:
            print(f"文件夹 '{folder_path}' 已存在")

        # 开始逐一处理step这个字典的各个元素
        # 首先保存图片
        if step['before_screenshot'] is not None:
            image_before = Image.fromarray(step['before_screenshot'])
        if step['after_screenshot'] is not None:
            image_after  = Image.fromarray(step['after_screenshot'])
        image_before_path = step_doc + 'image_before.png'
        image_after_path  = step_doc + 'image_after.png'
        image_before.save(image_before_path)
        image_after.save(image_after_path)

        # 图片键没有用了，剩下的直接json
        del step['before_screenshot']
        del step['after_screenshot']

        del step['before_element_list']
        del step['after_element_list']
        del step['action_raw_response']
        del step["summary_raw_response"]

        # ui元素要记得转化,把对象变成字典
        #step['before_element_list'] = [ui.__dict__ for ui in step['before_element_list']]
        #step['after_element_list'] = [ui.__dict__ for ui in step['after_element_list']]

        # 保存step为json文件
        json_path = step_doc + 'text.json'
        with open(json_path, 'w') as file:
            json.dump(step, file)

def check_action_output():
    pkl_name = 'raw_history_pkl/2024_11_21_16_10_30_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    for i, step in enumerate(history):
        print('第',i,'个动作')
        print(step['action_output'])
        print(type(step['action_output']))

def check_ui():
    pkl_name = 'raw_history_pkl/2024_11_22_15_45_19_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    for i, step in enumerate(history):
        if i != 1:
            continue
        for index, element in enumerate(step['before_element_list']):
            print(index)
            print(element)
        break

#check_action_output()

def _ui_list_different(list1, list2):
    set1 = set(list1)
    set2 = set(list2)

    # 计算不同的元素
    diff_elements = set1.symmetric_difference(set2)

    diff_elements_num = len(diff_elements)

    radio = diff_elements_num/len(list1)
    print('ui radio:',radio)

    if radio <= 0.1:
        # 不同的ui比例小于0.1
        return False
    else:
        return True

def _image_different(img1, img2):
    #img1,img2均是np.array   只比较像素点貌似不严谨。应该还要比较ui list
    # 计算像素点不同的地方 (逐元素比较)
    difference = img1 != img2

    # 统计不同的像素点数目
    num_diff_pixels = np.sum(difference)

    # 计算总像素点数
    total_pixels = img1.size

    # 计算不同像素点占总像素点的比例
    diff_ratio = num_diff_pixels / total_pixels

    print('image radio:',diff_ratio)

    if diff_ratio >= 0.001:
        # 确实是两张不一样的图
        return True
    else:
        return False

def filter_step():
    pkl_name = 'raw_history_pkl/2024_11_22_15_45_19_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    par_doc_name = 'processed_history/'
    current_time = datetime.now()# 获取当前时间
    formatted_time = current_time.strftime("%Y_%m_%d_%H_%M_%S")# 格式化时间为 年_月_日_时_分_秒
    doc_name = par_doc_name + formatted_time

    # 创建本个pkl文件的文件夹
    folder_path = Path(doc_name)
    if not folder_path.exists():
        folder_path.mkdir(parents=True)  # parents=True 允许创建多级目录
        print(f"文件夹 '{folder_path}' 已创建")
    else:
        print(f"文件夹 '{folder_path}' 已存在")

    for i, step in enumerate(history):
        # 创建本step的文件夹
        step_doc = doc_name + '/' + str(i) + '/'
        folder_path = Path(step_doc)
        if not folder_path.exists():
            folder_path.mkdir(parents=True)  # parents=True 允许创建多级目录
            print(f"文件夹 '{folder_path}' 已创建")
        else:
            print(f"文件夹 '{folder_path}' 已存在")

        # 开始逐一处理step这个字典的各个元素
        # 首先保存图片
        before, after = step['before_screenshot'], step['after_screenshot']
        ui_before, ui_after = step['before_element_list'], step['after_element_list']
        if before is not None and after is not None:
            if not _image_different(before, after) and not _ui_list_different(ui_before, ui_after):
                # 图像相同，那就不保存了
                continue
        if step['before_screenshot'] is not None:
            image_before = Image.fromarray(step['before_screenshot'])
            image_before_path = step_doc + 'image_before.png'
            image_before.save(image_before_path)
        if step['after_screenshot'] is not None:
            image_after  = Image.fromarray(step['after_screenshot'])
            image_after_path  = step_doc + 'image_after.png'
            image_after.save(image_after_path)

def _plot_dual_point(
    touch_x,
    touch_y,
    ax,
):
    """Plots a dual point action on the given matplotlib axis."""
    print("本次是点击动作,点击坐标",touch_x,touch_y)
    ax.scatter(
        touch_x,
        touch_y,
        s=550,
        linewidths=5,
        color=_ACTION_COLOR,
        marker='+',
    ) 
    return ax

def _get_annotation_positions(
    element_list
):
    """Processes the annotation positions into distinct bounding boxes.

    Args:
        element_list:由ui element类型对象组成的列表，可以提取出各个ui元素的边界信息

    Returns:
        A matrix of annotation positions with dimensions (# of annotations, 4),
        where each annotation bounding box takes the form (y, x, h, w).
    """
    positions = []

    for ui in element_list:
        # 记得筛选掉看不见的ui
        if ui.bbox_pixels is not None and ui.is_visible:
            #首先要获取左下角的那个点的位置
            x = ui.bbox_pixels.x_min
            y = ui.bbox_pixels.y_max
            h = ui.bbox_pixels.y_max - ui.bbox_pixels.y_min
            w = ui.bbox_pixels.x_max - ui.bbox_pixels.x_min
            positions.append((y,x,h,w))

    return positions

def _add_text(
    text, screen_width, screen_height, ax
):
  """Plots text on the given matplotlib axis."""
  t = ax.text(
      0.5 * screen_width,
      0.95 * screen_height,
      text,
      color='white',
      size=20,
      horizontalalignment='center',
      verticalalignment='center',
  )
  t.set_bbox(dict(facecolor=_ACTION_COLOR, alpha=0.9))

def _plot_action(
    action,  # 通过action.action_type来获取操作类型
    screen_height,
    screen_width,
    ax,
    bbox = None
):
    """Plots the example's action on the given matplotlib axis."""
    if action.action_type == 'click':
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    elif action.action_type == 'input_text':
        text = action.text
        _add_text(text, screen_width, screen_height, ax)
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    else:
        pass # 其他的暂时不画

# 展示before_screen加上边界和点击坐标的样子
def show_anno_img():
    pkl_name = 'raw_history_pkl/2024_11_22_15_45_19_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    par_doc_name = 'processed_history/'
    current_time = datetime.now()# 获取当前时间
    formatted_time = current_time.strftime("%Y_%m_%d_%H_%M_%S")# 格式化时间为 年_月_日_时_分_秒
    doc_name = par_doc_name + formatted_time

    # 创建本个pkl文件的文件夹
    folder_path = Path(doc_name)
    if not folder_path.exists():
        folder_path.mkdir(parents=True)  # parents=True 允许创建多级目录
        print(f"文件夹 '{folder_path}' 已创建")
    else:
        print(f"文件夹 '{folder_path}' 已存在")

    for i, step in enumerate(history):
        # 确认本次操作的主角
        image = step['before_screenshot']
        image_height = image.shape[0]
        image_width = image.shape[1]

        # 设置画布
        #print('设置画布')
        _, ax = plt.subplots(figsize=(8, 8))
        #print('设置中')
        ax.imshow(image)
        #print('设置ok')

        # 画上动作  首先是取出动作
        action_output = step['action_output']
        _, action = m3a_utils.parse_reason_action_output(action_output)
        try:
            converted_action = json_action.JSONAction(
                **agent_utils.extract_json(action),
            )
        except Exception as e:  # pylint: disable=broad-exception-caught
            print('Failed to convert the output to a valid action.')
            print(str(e))

        # 把动作画到图片里
        if converted_action.action_type == 'click' or converted_action.action_type == 'input_text':
            print("本次操作element:",step['before_element_list'][converted_action.index])
            bbox = step['before_element_list'][converted_action.index].bbox_pixels
            _plot_action(converted_action,image_height,image_width,ax,bbox)
        else:
            _plot_action(converted_action,image_height,image_width,ax)

        # 画出ui边界 首先是得到ui边界
        positions = _get_annotation_positions(step['before_element_list'])
        # 画上去
        for y, x, h, w in positions:
            rect = patches.Rectangle(
                (x, y), w, h, linewidth=1, edgecolor='r', facecolor='none'
            )
            ax.add_patch(rect)

        # 最后得到处理后的image
        plt.tight_layout()
        img_path = doc_name + '/' + str(i) + '.png'
        plt.savefig(img_path)

    
show_anno_img()



I am a beginner, and my code is a bit messy. I hope you can excuse me!

I followed the method in AITW to draw the bounding boxes and actions on the app screenshots. These functions seem to work fine on the AITW dataset

**Comment by LYXFOREVER** [comment]
I store the history as .pkl file in minimal_task_runner.py:

with open(path, 'wb') as file:
pickle.dump(agent.history, file)

Then in another read_history.py file I read the .pkl file:


def _plot_dual_point(
    touch_x,
    touch_y,
    ax,
):
    """Plots a dual point action on the given matplotlib axis."""
    print("本次是点击动作,点击坐标",touch_x,touch_y)
    ax.scatter(
        touch_x,
        touch_y,
        s=550,
        linewidths=5,
        color=_ACTION_COLOR,
        marker='+',
    ) 
    return ax

def _get_annotation_positions(
    element_list
):
    """Processes the annotation positions into distinct bounding boxes.

    Args:
        element_list:由UIElement对象组成的列表

    Returns:
        A matrix of annotation positions with dimensions (# of annotations, 4),
        where each annotation bounding box takes the form (y, x, h, w).
    """
    positions = []

    for ui in element_list:
        # 记得筛选掉看不见的ui
        if ui.bbox_pixels is not None and ui.is_visible:
            #首先要获取左下角的那个点的位置
            x = ui.bbox_pixels.x_min
            y = ui.bbox_pixels.y_max
            h = ui.bbox_pixels.y_max - ui.bbox_pixels.y_min
            w = ui.bbox_pixels.x_max - ui.bbox_pixels.x_min
            positions.append((y,x,h,w))

    return positions

def _add_text(
    text, screen_width, screen_height, ax
):
  """Plots text on the given matplotlib axis."""
  t = ax.text(
      0.5 * screen_width,
      0.95 * screen_height,
      text,
      color='white',
      size=20,
      horizontalalignment='center',
      verticalalignment='center',
  )
  t.set_bbox(dict(facecolor=_ACTION_COLOR, alpha=0.9))

def _plot_action(
    action,  # 通过action.action_type来获取操作类型
    screen_height,
    screen_width,
    ax,
    bbox = None
):
    """Plots the example's action on the given matplotlib axis."""
    if action.action_type == 'click':
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    elif action.action_type == 'input_text':
        text = action.text
        _add_text(text, screen_width, screen_height, ax)
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    else:
        pass # 其他的暂时不画

# 展示before_screen加上边界和点击坐标的样子
def show_anno_img():
    pkl_name = 'raw_history_pkl/2024_11_22_15_45_19_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    par_doc_name = 'processed_history/'
    current_time = datetime.now()# get current time
    formatted_time = current_time.strftime("%Y_%m_%d_%H_%M_%S")
    doc_name = par_doc_name + formatted_time

    # 创建本个pkl文件的文件夹
    folder_path = Path(doc_name)
    if not folder_path.exists():
        folder_path.mkdir(parents=True)  # create doc
        print(f"文件夹 '{folder_path}' 已创建")
    else:
        print(f"文件夹 '{folder_path}' 已存在")

    for i, step in enumerate(history):
        # 确认本次操作的主角
        image = step['before_screenshot']
        image_height = image.shape[0]
        image_width = image.shape[1]

        # 设置画布
        #print('设置画布')
        _, ax = plt.subplots(figsize=(8, 8))
        #print('设置中')
        ax.imshow(image)
        #print('设置ok')

        # 画上动作  首先是取出动作
        action_output = step['action_output']
        _, action = m3a_utils.parse_reason_action_output(action_output)
        try:
            converted_action = json_action.JSONAction(
                **agent_utils.extract_json(action),
            )
        except Exception as e:  # pylint: disable=broad-exception-caught
            print('Failed to convert the output to a valid action.')
            print(str(e))

        # 把动作画到图片里
        if converted_action.action_type == 'click' or converted_action.action_type == 'input_text':
            print("本次操作element:",step['before_element_list'][converted_action.index])
            bbox = step['before_element_list'][converted_action.index].bbox_pixels
            _plot_action(converted_action,image_height,image_width,ax,bbox)
        else:
            _plot_action(converted_action,image_height,image_width,ax)

        # 画出ui边界 首先是得到ui边界
        positions = _get_annotation_positions(step['before_element_list'])
        # 画上去
        for y, x, h, w in positions:
            rect = patches.Rectangle(
                (x, y), w, h, linewidth=1, edgecolor='r', facecolor='none'
            )
            ax.add_patch(rect)

        # 最后得到处理后的image
        plt.tight_layout()
        img_path = doc_name + '/' + str(i) + '.png'
        plt.savefig(img_path)

    
show_anno_img()



I am a beginner, and my code is a bit messy. I hope you can excuse me!

I followed the method in AITW to draw the bounding boxes and actions on the app screenshots. These functions seem to work fine on the AITW dataset.

**Comment by LYXFOREVER** [comment]
I store the history as .pkl file in minimal_task_runner.py:

with open(path, 'wb') as file:
pickle.dump(agent.history, file)

Then in another read_history.py file I read the .pkl file:

def _plot_dual_point(
    touch_x,
    touch_y,
    ax,
):
    """Plots a dual point action on the given matplotlib axis."""
    print("本次是点击动作,点击坐标",touch_x,touch_y)
    ax.scatter(
        touch_x,
        touch_y,
        s=550,
        linewidths=5,
        color=_ACTION_COLOR,
        marker='+',
    ) 
    return ax

def _get_annotation_positions(
    element_list
):
    """Processes the annotation positions into distinct bounding boxes.

    Args:
        element_list:由UIElement对象组成的列表

    Returns:
        A matrix of annotation positions with dimensions (# of annotations, 4),
        where each annotation bounding box takes the form (y, x, h, w).
    """
    positions = []

    for ui in element_list:
        # 记得筛选掉看不见的ui
        if ui.bbox_pixels is not None and ui.is_visible:
            #首先要获取左下角的那个点的位置
            x = ui.bbox_pixels.x_min
            y = ui.bbox_pixels.y_max
            h = ui.bbox_pixels.y_max - ui.bbox_pixels.y_min
            w = ui.bbox_pixels.x_max - ui.bbox_pixels.x_min
            positions.append((y,x,h,w))

    return positions

def _add_text(
    text, screen_width, screen_height, ax
):
  """Plots text on the given matplotlib axis."""
  t = ax.text(
      0.5 * screen_width,
      0.95 * screen_height,
      text,
      color='white',
      size=20,
      horizontalalignment='center',
      verticalalignment='center',
  )
  t.set_bbox(dict(facecolor=_ACTION_COLOR, alpha=0.9))

def _plot_action(
    action,  # 通过action.action_type来获取操作类型
    screen_height,
    screen_width,
    ax,
    bbox = None
):
    """Plots the example's action on the given matplotlib axis."""
    if action.action_type == 'click':
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    elif action.action_type == 'input_text':
        text = action.text
        _add_text(text, screen_width, screen_height, ax)
        print(bbox)
        x,y = bbox.center
        return _plot_dual_point(
            x, y, ax
        )
    else:
        pass # 其他的暂时不画


def show_anno_and_action_img():
    pkl_name = 'raw_history_pkl/2024_11_22_15_45_19_history.pkl'
    with open(pkl_name, 'rb') as f:
        history = pickle.load(f)

    par_doc_name = 'processed_history/'
    current_time = datetime.now()# get current time
    formatted_time = current_time.strftime("%Y_%m_%d_%H_%M_%S")
    doc_name = par_doc_name + formatted_time

    # 创建本个pkl文件的文件夹
    folder_path = Path(doc_name)
    if not folder_path.exists():
        folder_path.mkdir(parents=True)  # create doc
        print(f"文件夹 '{folder_path}' 已创建")
    else:
        print(f"文件夹 '{folder_path}' 已存在")

    for i, step in enumerate(history):
        # 确认本次操作的主角
        image = step['before_screenshot']
        image_height = image.shape[0]
        image_width = image.shape[1]

        # 设置画布
        #print('设置画布')
        _, ax = plt.subplots(figsize=(8, 8))
        #print('设置中')
        ax.imshow(image)
        #print('设置ok')

        # 画上动作  首先是取出动作
        action_output = step['action_output']
        _, action = m3a_utils.parse_reason_action_output(action_output)
        try:
            converted_action = json_action.JSONAction(
                **agent_utils.extract_json(action),
            )
        except Exception as e:  # pylint: disable=broad-exception-caught
            print('Failed to convert the output to a valid action.')
            print(str(e))

        # 把动作画到图片里
        if converted_action.action_type == 'click' or converted_action.action_type == 'input_text':
            print("本次操作element:",step['before_element_list'][converted_action.index])
            bbox = step['before_element_list'][converted_action.index].bbox_pixels
            _plot_action(converted_action,image_height,image_width,ax,bbox)
        else:
            _plot_action(converted_action,image_height,image_width,ax)

        # 画出ui边界 首先是得到ui边界
        positions = _get_annotation_positions(step['before_element_list'])
        # 画上去
        for y, x, h, w in positions:
            rect = patches.Rectangle(
                (x, y), w, h, linewidth=1, edgecolor='r', facecolor='none'
            )
            ax.add_patch(rect)

        # 最后得到处理后的image
        plt.tight_layout()
        img_path = doc_name + '/' + str(i) + '.png'
        plt.savefig(img_path)

    
show_anno_and_action_img()

I am a beginner, and my code is a bit messy. I hope you can excuse me!

I followed the method in AITW to draw the bounding boxes and actions on the app screenshots. These functions seem to work fine on the AITW dataset.

**Comment by crawles** [comment]
NP. I am unable to figure out exactly from your code. We have some plotting code that may help you.

from android_world.utils import plotting
from android_world.env import interface

```
checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
episodes = checkpointer.load()
episode = episodes[0]
with open('/tmp/result.html', 'w') as f:
  # T3A.
  # data = m3a_utils.generate_single_task_html_for_gpt4_text(episode)
  # M3A.
  data = m3a_utils.generate_single_task_html_for_m3a(episode)

  f.write(data)
  ```

```
from android_world.utils import plotting
from android_world.env import interface

checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
episodes = checkpointer.load()
episode = episodes[0]
print(episode['episode_data'].keys())
screenshot = episode['episode_data']['before_screenshot'][0]
ui_elements = episode['episode_data']['before_element_list'][0]

state = interface.State(pixels=screenshot, ui_elements=ui_elements, forest=None)

axs = plotting.plot_ui_elements(state)
```

**Comment by LYXFOREVER** [comment]
> NP. I am unable to figure out exactly from your code. We have some plotting code that may help you.
> 
> from android_world.utils import plotting from android_world.env import interface
> 
> ```
> checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
> episodes = checkpointer.load()
> episode = episodes[0]
> with open('/tmp/result.html', 'w') as f:
>   # T3A.
>   # data = m3a_utils.generate_single_task_html_for_gpt4_text(episode)
>   # M3A.
>   data = m3a_utils.generate_single_task_html_for_m3a(episode)
> 
>   f.write(data)
> ```
> 
> ```
> from android_world.utils import plotting
> from android_world.env import interface
> 
> checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
> episodes = checkpointer.load()
> episode = episodes[0]
> print(episode['episode_data'].keys())
> screenshot = episode['episode_data']['before_screenshot'][0]
> ui_elements = episode['episode_data']['before_element_list'][0]
> 
> state = interface.State(pixels=screenshot, ui_elements=ui_elements, forest=None)
> 
> axs = plotting.plot_ui_elements(state)
> ```

May I ask what is checkpointer_lib?

**Comment by LYXFOREVER** [comment]
I have solved this problem! It does be a plotting error! Thank you

> NP. I am unable to figure out exactly from your code. We have some plotting code that may help you.
> 
> from android_world.utils import plotting from android_world.env import interface
> 
> ```
> checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
> episodes = checkpointer.load()
> episode = episodes[0]
> with open('/tmp/result.html', 'w') as f:
>   # T3A.
>   # data = m3a_utils.generate_single_task_html_for_gpt4_text(episode)
>   # M3A.
>   data = m3a_utils.generate_single_task_html_for_m3a(episode)
> 
>   f.write(data)
> ```
> 
> ```
> from android_world.utils import plotting
> from android_world.env import interface
> 
> checkpointer = checkpointer_lib.IncrementalCheckpointer(YOUR_PATH)
> episodes = checkpointer.load()
> episode = episodes[0]
> print(episode['episode_data'].keys())
> screenshot = episode['episode_data']['before_screenshot'][0]
> ui_elements = episode['episode_data']['before_element_list'][0]
> 
> state = interface.State(pixels=screenshot, ui_elements=ui_elements, forest=None)
> 
> axs = plotting.plot_ui_elements(state)
> ```
