### ISSUE TITLE
Add new task

### ISSUE THREAD

**Issue by zhiyuanc2001** [google-research/android_world#58]
Hi, thanks for the outstanding work.
Now, I want to add more tasks, (for example, add new tasks of ``Simple Calendar Pro`` App), and how can I achieve the goal? Do I need to make changes to the ``android_env`` package?
Thanks. :-)

**Comment by crawles** [comment]
Hello. I am glad you are finding AndroidWorld useful.
To create a calendar task, you can look at the existing [tasks](https://github.com/google-research/android_world/blob/main/android_world/task_evals/single/calendar/calendar.py) for calendar. You can make use of the validation functions we have in [common validators](https://github.com/google-research/android_world/tree/main/android_world/task_evals/common_validators). For the calendar tasks, and many others, ultimately it requires inspecting a SQLite database. So there is a lot of flexibility.

To test the new tasks you create, create a new registry, or inherit from [ours](https://github.com/google-research/android_world/blob/main/android_world/registry.py) and add your tasks there.

**Comment by crawles** [comment]
We have also added a guide for adding new tasks: https://github.com/google-research/android_world/blob/main/docs/tasks_guide.md
