### ISSUE TITLE
Is MarkorTranscribeVideo a valid task?

### ISSUE THREAD

**Issue by boyugou** [google-research/android_world#59]
Hello!

I got this FileNotFoundError when runing 'MarkorTranscribeVideo':

```
  File "/Users/username/PycharmProjects/android_world/android_world/suite_utils.py", line 229, in _run_task
    task.initialize_task(env)
  File "/Users/username/PycharmProjects/android_world/android_world/task_evals/single/markor.py", line 859, in initialize_task
    user_data_generation.write_video_file_to_device(
  File "/Users/username/PycharmProjects/android_world/android_world/task_evals/utils/user_data_generation.py", line 283, in write_video_file_to_device
    file_utils.copy_data_to_device(
  File "/Users/username/PycharmProjects/android_world/android_world/utils/file_utils.py", line 398, in copy_data_to_device
    raise FileNotFoundError(f"{local_path} does not exist.")
FileNotFoundError: /tmp/ZwUN_moment_70_.mp4 does not exist.
agent_nameîå	m3a_gpt4vîua.
```

Is this task actually valid or NaN? and btw, in the paper's reported score, whether NaN is counted as failure or not?

**Comment by boyugou** [comment]
There are also some other tasks that cannot be tested. I'm not sure if it's because I messed up the code.

**Comment by boyugou** [comment]
Hi. Very thanks to your swift response! @crawles 

I was using Mac OS. It's great that you can confirm it can work well on Linux. I'm actually switching to linux right now.

**Comment by boyugou** [comment]
There are multiple tasks that I will encounter the two issues I mentioned above. I will check again whether they still happen on linux soon.

**Comment by crawles** [comment]
Awesome! I hope it works for your Linux setup, let us know. Will try to repro on Mac.

cc:  @clink42

**Comment by boyugou** [comment]
Most of issues were addressed after switching to Linux. Although I'm not very sure if that is due to the platform environments. 

I do observe that after some runs and manual stop, "RecipeDeleteDuplicateRecipes", "RecipeDeleteDuplicateRecipes2", etc. show the db error. But it seems can be easily addressed by change to a new checkpoint_dir.

**Comment by crawles** [comment]
Glad to hear most of the issues are resolved.

Re: `MarkorTranscribeVideo`, I just tried a fresh install on a Mac M1 and it worked successfully.

```
[I] ~/D/a/android_world ❯❯❯ python minimal_task_runner.py --task=MarkorTranscribeVideo          (android_world)  main ✱ ◼
/Users/chrisrawles/miniforge3/envs/android_world/lib/python3.11/site-packages/pydub/utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1722113887.859227  883254 trace.cc:91] Unknown tracer: none
W0727 16:58:29.822660 8432487424 android_world_controller.py:97] Could not get a11y tree, retrying.
W0727 16:58:30.828202 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
Goal: Transcribe the contents of video footage_84_HD_final.mp4 by watching it in VLC player (located in Download) and writing the sequence of strings shown on each frame to the text file footage_84_HD_final_transcription.txt in Markor as a comma separated list. For example, if the first frame shows the text "edna" and the second frame shows the text "pineapple", then the text file should contain only the following text: "edna, pineapple".
Pausing 1.0 seconds before grabbing state.
W0727 16:58:37.468630 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
W0727 16:58:37.538780 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
Invalid direction
Pausing 1.0 seconds before grabbing state.
E0000 00:00:1722113918.595870  883254 tcp_posix.cc:596] recvmsg encountered uncommon error: Message too long
W0727 16:58:38.648245 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
W0727 16:58:38.715077 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
Pausing 1.0 seconds before grabbing state.
W0727 16:58:39.843396 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
E0000 00:00:1722113919.877598  883254 tcp_posix.cc:596] recvmsg encountered uncommon error: Message too long
W0727 16:58:39.917370 8432487424 representation_utils.py:157] screen_size=None, no normalized bbox for elements.
Task Failed ❌; Transcribe the contents of video footage_84_HD_final.mp4 by watching it in VLC player (located in Download) and writing the sequence of strings shown on each frame to the text file footage_84_HD_final_transcription.txt in Markor as a comma separated list. For example, if the first frame shows the text "edna" and the second frame shows the text "pineapple", then the text file should contain only the following text: "edna, pineapple".
```

A few potential culprits:
1. Maybe `ffmpeg` is not installed. Oddly enough, I see "Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work”, but it still correctly writes the files.
2. A codec issue, i.e. mp4 may not as well supported on Mac
3. Opencv video writing not working correctly.

If you encounter it again, I would kindly request you post any additional logs you have.

Regarding the db issue, I think you are right previous tasks are affecting the current task. Will dig into it

**Comment by crawles** [comment]
I was actually able to reproduce the VLC error, and, on my end at least, it's due to `ffmpeg` not being installed.

**Comment by crawles** [comment]
@boyugou we also submitted a fix for the database clearing before the SQLite tasks. This may be needed if for some reason, the snapshots were not correctly created during emulator set up. I would expect this should fix your issue, but please let us know if not

**Comment by boyugou** [comment]
Sounds pretty good. Thanks so much for the assistance.

I have completed most of my experiments on Linux, although not perfectly smoothly. Besides the issues mentioned above, these are the problems I encountered while testing:

- Several tasks fail to execute (NaN scores);

- The memory often crashes suddenly halfway (3.2GB --> 16GB --> explode). I'm almost sure it happens during loading one task(in the middle)'s saved pkl checkpoints, but I couldn't identify which task is causing the problem. (It might be due to the changes I made to the screenshots saved to it. However, my changes work well on other tasks.) Therefore, I have to run the tasks in 2-3 splits each time. 

- Additionally, it sometimes gets stuck (during adb operations?), so I need to monitor it manually and restart it occasionally.

I don't have much time to investigate the reasons at the moment because these issues haven't significantly impacted my experiments. It seems that completely failed tasks are not something GPT can handle. 

I greatly appreciate your assistance. I will spend more time next week to thoroughly investigate the causes and see if I can contribute to this excellent benchmark in some way.

**Comment by crawles** [comment]
Thank you for all the helpful information. The saving issue can certainly
be fixed, by logging metadata in a separate file. In the meantime your
approach of splitting it up is reasonable.

Regarding the tasks with NaN, when you get a chance, could you send me the
exception info for those tasks contained in the pickle files? No rush. You
should be able to loop thru the loaded checkpoints and print
‘exception_info’. FYI, we log the exceptions here:
https://github.com/google-research/android_world/blob/main/android_world/suite_utils.py#L262

For the adb stuff, we may be able to just increase the timeout. It would be
better to figure out the root cause, which will try to do.

Chris
