### ISSUE TITLE
Where is "task" and "joplin"?

### ISSUE THREAD

**Issue by WentaoYan1453** [google-research/android_world#64]
Thank you for this excellent project. I have a question: you mentioned "task" and "joplin" in the papers, task_app_utils, and joplin_app_utils, but why are they not appearing in the registry?

**Comment by clink42** [comment]
The Tasks and Joplin apps only have "Information retrieval" tasks. Those tasks are defined as protos here:
https://github.com/google-research/android_world/blob/main/android_world/task_evals/information_retrieval/proto/tasks.textproto

Tasks app tasks contain "Tasks" at the start of their name, e.g. "TasksHighPriorityTasks", Joplin tasks contain "Notes" e.g "NotesRecipeIngredientCount"
